name: Checks

on:
    pull_request:
        branches: [main]
    push:
        branches: [main]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
            
            - name: Set up Python
              uses: actions/setup-python@v5
            #   with:
            #     python-version: "3.11.6"
            
            # - name: Install Poetry
            #   run: |
            #     make install-poetry
            #     echo "$HOME/.local/bin" >> $GITHUB_PATH
            
            - name: Install dependencies
              run: |
                make poetry
                source .venv/bin/activate
                pip list